name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK for Android
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: '33.0.0'
          target: 'android-33'

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Run KtLint Format to fix any Kotlin style issues automatically
      - name: Run KtLint Format
        run: ./gradlew ktlintFormat

      # Run KtLint Check to verify all Kotlin files meet style guidelines
      - name: Run KtLint Check
        run: ./gradlew ktlintCheck

      # Run Java Lint to check for Java style and quality issues
      - name: Run Java Lint
        run: ./gradlew lint

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
